### ISSUE TITLE
Possible 1.20.1 version?

### ISSUE THREAD

**Issue by porridge-eater** [mineTomek/Panoramas#3]
This looks great. Any possibility there'll be a 1.20.1 version, too?

**Comment by mineTomek** [comment]
I can make a build for 1.20.1 for you manually, but I don't really know how to manage multiple Minecraft versions simultaneously on one repository. I will be looking into that today so expect an official support for both 1.20.1 and 1.20.4 (and probably more requested versions) soon.

**Comment by porridge-eater** [comment]
Oh, that sounds great. Thank you for considering it! I hope it goes well.

**Comment by mineTomek** [comment]
I'm running into a few issues with the conversion to 1.20.1. I can give you a working version earlier, but there won't be buttons for applying panoramas in the world and server select screen, you'll have to use the resource pack selector for that. When I get multiple versions working simultaneously it will be all working.

**Comment by mineTomek** [comment]
[panoramas-0.0.3.jar.zip](https://github.com/mineTomek/Panoramas/files/14157601/panoramas-0.0.3.jar.zip)
Here's the quick 1.20.1 version. As I said, it has a few limitations for now, but it works.

It works on my version with my world as the panorama.
<img width="1682" alt="My world as the panorama" src="https://github.com/mineTomek/Panoramas/assets/102610423/9287535e-f024-47df-8c69-3579ea1ab771">

**Comment by porridge-eater** [comment]
Thank you. I appreciate the early build. If it works this well with limited features, I'm excited to test out the full build when you get around to it. Again, I appreciate you responding to my suggestion!

**Comment by porridge-eater** [comment]
Apologies for closing these; I'm not familiar with using github.

**Comment by mineTomek** [comment]
Don't worry. It doesn't break anything it's a mainly visual thing
